"""Protocol buffer generated modules for semantic analyzer."""

# These are generated by protoc from semantic_analyzer.proto
try:
    from socialseed_e2e.agents.semantic_analyzer.proto.semantic_analyzer_pb2 import *
    from socialseed_e2e.agents.semantic_analyzer.proto.semantic_analyzer_pb2_grpc import *
except ImportError:
    # If protobuf files are not generated yet, provide stub imports
    pass
