"""Console configuration for socialseed-e2e framework.

This module provides a cross-platform Console instance that handles
Windows encoding issues properly for emoji characters.
"""

import os
import platform
import sys
from io import StringIO
from rich.console import Console
from rich.markup import escape

IS_WINDOWS = platform.system() == "Windows"

# Set UTF-8 encoding for stdout/stderr on Windows if not already set
if IS_WINDOWS and sys.stdout.encoding != 'utf-8':
    try:
        os.environ['PYTHONIOENCODING'] = 'utf-8'
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass  # Ignore if reconfigure fails

# Emoji replacement map for Windows legacy consoles
# Also includes box drawing characters and other Unicode symbols
UNICODE_REPLACEMENTS = {
    # Emojis
    '🚀': '[RUN]',
    '✅': '[OK]',
    '❌': '[X]',
    '⚠️': '[!]',
    '📋': '[LIST]',
    '💡': '[TIP]',
    '🎯': '[GOAL]',
    '🔧': '[TOOL]',
    '📝': '[NOTE]',
    '🔍': '[SEARCH]',
    '📊': '[STATS]',
    '⏱️': '[TIME]',
    '🔒': '[LOCK]',
    '🔓': '[UNLOCK]',
    '❤️': '[HEART]',
    '⭐': '[STAR]',
    '🎉': '[Party]',
    '📦': '[PKG]',
    '🌐': '[WEB]',
    '🔗': '[LINK]',
    '📁': '[DIR]',
    '📄': '[FILE]',
    '🛠️': '[WRENCH]',
    '✨': '[SPARKLE]',
    '🔄': '[SYNC]',
    '📈': '[UP]',
    '📉': '[DOWN]',
    '🔀': '[MERGE]',
    '🗑️': '[DEL]',
    '🎨': '[ART]',
    '🔥': '[FIRE]',
    '💻': '[DEV]',
    '🌟': '[GLOW]',
    '⚡': '[ZAP]',
    '🎮': '[GAME]',
    '📚': '[BOOK]',
    '🎓': '[SCHOOL]',
    '🏆': '[TROPHY]',
    '🎯': '[TARGET]',
    '💬': '[CHAT]',
    '🔵': '[BLUE]',
    '🔴': '[RED]',
    '🟢': '[GREEN]',
    '🟡': '[YELLOW]',
    '⚪': '[WHITE]',
    '⚫': '[BLACK]',
    '🔶': '[ORANGE]',
    '🟣': '[PURPLE]',
    '🟤': '[BROWN]',
    '👤': '[USER]',
    '👥': '[USERS]',
    '🔑': '[KEY]',
    '🕐': '[TIME1]',
    '🕑': '[TIME2]',
    '🕒': '[TIME3]',
    '💾': '[DISK]',
    '📀': '[CD]',
    '📻': '[RADIO]',
    '📺': '[TV]',
    '🎥': '[VIDEO]',
    '📷': '[CAM]',
    '🔊': '[VOL+]',
    '🔇': '[MUTE]',
    '📧': '[EMAIL]',
    '📨': '[MAIL]',
    '📩': '[ENVELOPE]',
    '📤': '[OUT]',
    '📥': '[IN]',
    '💼': '[WORK]',
    '📎': '[CLIP]',
    '📌': '[PIN]',
    '🔖': '[MARK]',
    '🏷️': '[TAG]',
    '📋': '[CLIPBOARD]',
    '📃': '[PAGE]',
    '📄': '[DOC]',
    '📑': '[TABS]',
    '🔍': '[MAGNIFIER]',
    '🔎': '[MAGNIFIER+]',
    '💰': '[MONEY]',
    '💵': '[CASH]',
    '💳': '[CARD]',
    '💹': '[CHART]',
    '📆': '[CAL]',
    '📅': '[DATE]',
    '⏰': '[ALARM]',
    '⏲️': '[TIMER]',
    '⏳': '[HOURGLASS]',
    '🔓': '[UNLOCKED]',
    '🔐': '[LOCKED]',
    '🔑': '[PASSKEY]',
    '🔒': '[SECURE]',
    '🛡️': '[SHIELD]',
    '⚔️': '[SWORDS]',
    '💊': '[PILL]',
    '🩺': '[STETHOSCOPE]',
    '🧪': '[TESTTUBE]',
    '🔬': '[MICROSCOPE]',
    '🔭': '[TELESCOPE]',
    '🌡️': '[THERMO]',
    '💧': '[DROP]',
    '🔥': '[FLAME]',
    '💨': '[WIND]',
    '❄️': '[SNOW]',
    '☀️': '[SUN]',
    '🌙': '[MOON]',
    '⭐': '[DOT]',
    '🌈': '[RAINBOW]',
    '☁️': '[CLOUD]',
    '🌧️': '[RAIN]',
    '⛈️': '[STORM]',
    '🌪️': '[TORNADO]',
    '🌫️': '[FOG]',
    '💨': '[FAST]',
    '🌊': '[WAVE]',
    '🏖️': '[BEACH]',
    '🏔️': '[MOUNTAIN]',
    '🌋': '[VOLCANO]',
    '🏕️': '[CAMPING]',
    '🏠': '[HOME]',
    '🏢': '[BUILDING]',
    '🏥': '[HOSPITAL]',
    '🏦': '[BANK]',
    '🏪': '[STORE]',
    '🏰': '[CASTLE]',
    '⛪': '[CHURCH]',
    '🕌': '[MOSQUE]',
    '🛕': '[TEMPLE]',
    '⛩️': '[SHINTO]',
    '🗽': '[STATUE]',
    '🎡': '[FERRIS]',
    '🎢': '[ROLLER]',
    '🎠': '[CAROUSEL]',
    '🏟️': '[STADIUM]',
    '🎭': '[MASKS]',
    '🎪': '[CIRCUS]',
    '🎨': '[PALETTE]',
    '🎬': '[CLAPPER]',
    '🎤': '[MIC]',
    '🎧': '[HEADPHONES]',
    '🎹': '[KEYBOARD]',
    '🎸': '[GUITAR]',
    '🎺': '[TRUMPET]',
    '🥁': '[DRUM]',
    '🎷': '[SAX]',
    '🎻': '[VIOLIN]',
    '🎲': '[DICE]',
    '🎯': '[DART]',
    '🎳': '[BOWLING]',
    '🏀': '[BASKET]',
    '⚽': '[SOCCER]',
    '🏈': '[FOOTBALL]',
    '⚾': '[BASEBALL]',
    '🎾': '[TENNIS]',
    '🏐': '[VOLLEY]',
    '🏉': '[RUGBY]',
    '🎱': '[8BALL]',
    '⛳': '[GOLF]',
    '🏊': '[SWIM]',
    '🚴': '[BIKE]',
    '🏃': '[RUNNER]',
    '🧘': '[YOGA]',
    '🤸': '[GYMNAST]',
    '⛷️': '[SKI]',
    '🏂': '[SNOWBOARD]',
    '🛷': '[SLED]',
    '⛸️': '[SKATE]',
    '🏋️': '[WEIGHT]',
    '🤺': '[FENCING]',
    '🤼': '[WRESTLE]',
    '🤸': '[CARTWHEEL]',
    '⛹️': '[BALL]',
    '🏌️': '[GOLFER]',
    '🚣': '[ROW]',
    '🧗': '[CLIMB]',
    '🏇': '[JOCKEY]',
    '🛤️': '[RAILWAY]',
    '🛣️': '[HIGHWAY]',
    '⛽': '[FUEL]',
    '🚗': '[CAR]',
    '🚕': '[TAXI]',
    '🚙': '[SUV]',
    '🚌': '[BUS]',
    '🚎': '[TROLLY]',
    '🏎️': '[RACE]',
    '🚓': '[POLICE]',
    '🚑': '[AMBULANCE]',
    '🚒': '[FIRETRUCK]',
    '🚐': '[VAN]',
    '🚚': '[TRUCK]',
    '🚛': '[LORRY]',
    '🚜': '[TRACTOR]',
    '🛴': '[SCOOTER]',
    '🚲': '[BICYCLE]',
    '🛵': '[MOTO]',
    '🏍️': '[MOTORCYCLE]',
    '🚏': '[BUSSTOP]',
    '🛤️': '[TRACK]',
    '⛵': '[SAILBOAT]',
    '🚤': '[SPEEDBOAT]',
    '🛳️': '[SHIP]',
    '⛴️': '[FERRY]',
    '🚢': '[BOAT]',
    '✈️': '[PLANE]',
    '🛫': '[TAKEOFF]',
    '🛬': '[LANDING]',
    '🚀': '[ROCKET]',
    '🛰️': '[SATELLITE]',
    '💺': '[SEAT]',
    '🛎️': '[BELL]',
    '🚪': '[DOOR]',
    '🛋️': '[COUCH]',
    '🛏️': '[BED]',
    '🛁': '[BATH]',
    '🚽': '[TOILET]',
    '🚿': '[SHOWER]',
    '🧴': '[LOTION]',
    '🧷': '[PIN]',
    '🧹': '[BROOM]',
    '🧺': '[BASKET]',
    '🧻': '[ROLL]',
    '🧼': '[SOAP]',
    '🧽': '[SPONGE]',
    '🧯': '[VACUUM]',
    '🛒': '[CART]',
    '🎁': '[GIFT]',
    '🎈': '[BALLOON]',
    '🎀': '[RIBBON]',
    '🎊': '[CONFETTI]',
    '🎉': '[PARTY]',
    '✂️': '[SCISSORS]',
    '📎': '[PAPERCLIP]',
    '✒️': '[PEN]',
    '✏️': '[PENCIL]',
    '🖊️': '[PEN]',
    '🖋️': '[INK]',
    '📝': '[MEMO]',
    '📌': '[PUSHPIN]',
    '📍': '[PIN]',
    '📏': '[RULER]',
    '📐': '[TRI-RULER]',
    '✂️': '[CUT]',
    '🗃️': '[FOLDER]',
    '🗄️': '[CABINET]',
    '🗑️': '[TRASH]',
    '🔧': '[WRENCH]',
    '🔨': '[HAMMER]',
    '⚒️': '[PICK-HAMMER]',
    '🛠️': '[TOOLS]',
    '⛏️': '[PICK]',
    '🔩': '[BOLT]',
    '🔗': '[CHAIN]',
    '⚙️': '[GEAR]',
    '🗜️': '[CLAMP]',
    '⚖️': '[SCALES]',
    '🔗': '[LINK]',
    '⚡': '[LIGHTNING]',
    '🔕': '[NO-BELL]',
    '🔔': '[BELL]',
    '🔓': '[UNLOCK]',
    '🔒': '[LOCK]',
    '🔑': '[KEY]',
    '🕯️': '[CANDLE]',
    '💡': '[IDEA]',
    '🔦': '[FLASHLIGHT]',
    '🔆': '[BRIGHT+]',
    '🔅': '[BRIGHT-]',
    '🔔': '[DING]',
    '📯': '[HORN]',
    '🎙️': '[MIC-STAND]',
    '📡': '[ANTENNA]',
    '📻': '[RADIO]',
    '🔊': '[SPEAKER+]',
    '🔉': '[SPEAKER-]',
    '🔈': '[SPEAKER]',
    '🔇': '[MUTED]',
    '📣': '[MEGAPHONE]',
    '💬': '[SPEECH]',
    '💭': '[THOUGHT]',
    '🗯️': '[RAGE]',
    '💢': '[ANGER]',
    '😠': '[ANGRY]',
    '😡': '[PISSED]',
    '🤬': '[CURSE]',
    '😈': '[DEVIL]',
    '👿': '[IMP]',
    '💀': '[SKULL]',
    '☠️': '[DEAD]',
    '💩': '[POOP]',
    '🤡': '[CLOWN]',
    '👹': '[OGRE]',
    '👺': '[GOBLIN]',
    '👻': '[GHOST]',
    '👽': '[ALIEN]',
    '🤖': '[ROBOT]',
    '💻': '[LAPTOP]',
    '🖥️': '[DESKTOP]',
    '🖨️': '[PRINTER]',
    '⌨️': '[KEYBOARD]',
    '🖱️': '[MOUSE]',
    '🖲️': '[TRACKBALL]',
    '💽': '[DISKETTE]',
    '💾': '[FLOPPY]',
    '💿': '[CD]',
    '📀': '[DVD]',
    '🧮': '[ABACUS]',
    '🎥': '[CAMCORDER]',
    '🎞️': '[FILM]',
    '📽️': '[PROJECTOR]',
    '🎬': '[MOVIE]',
    '📺': '[TV]',
    '📷': '[CAMERA]',
    '📸': '[CAMERA+]',
    '📹': '[VIDEO]',
    '📼': '[VHS]',
    '🔊': '[VOL]',
    '💡': '[BULB]',
    '📔': '[NOTEBOOK]',
    '📒': '[LEDGER]',
    '📕': '[BOOK-]',
    '📗': '[BOOK_GREEN]',
    '📘': '[BOOK_BLUE]',
    '📙': '[BOOK_ORANGE]',
    '📚': '[BOOKS]',
    '📓': '[NOTES]',
    '📒': '[TACKLE]',
    '📃': '[DOC+]',
    '📜': '[SCROLL]',
    '📄': '[PAGE_FACE]',
    '📰': '[NEWSPAPER]',
    '🗞️': '[PRESS]',
    '📑': '[TABS]',
    '🔖': '[BOOKMARK]',
    '🏷️': '[TAG]',
    '💰': '[MONEY_BAG]',
    '🪙': '[COIN]',
    '💴': '[YEN]',
    '💵': '[DOLLAR]',
    '💶': '[EURO]',
    '💷': '[POUND]',
    '💸': '[MONEY_FLY]',
    '💳': '[CARD_BANK]',
    '💹': '[CHART_INCREASE]',
    '📧': '[ENVELOPE]',
    '📩': '[ENVELOPE_OUT]',
    '📨': '[ENVELOPE_IN]',
    '📬': '[MAILBOX]',
    '📭': '[POSTBOX]',
    '📮': '[POST_STAMP]',
    '📯': '[POST_HORN]',
    '📜': '[SCROLL]',
    '📃': '[SHEET]',
    '📄': '[PAPER]',
    '📰': '[PRESS]',
    '🗾': '[MAP_JP]',
    '🗺️': '[MAP]',
    '🗿': '[MOAI]',
    '🗽': '[STATUE]',
    '🗼': '[TOWER]',
    '🏰': '[EUROPEAN_CASTLE]',
    '🏯': '[JAPANESE_CASTLE]',
    '🏟️': '[STADIUM]',
    '🎡': '[FERRIS]',
    '🎢': '[ROLLER_COASTER]',
    '🎠': '[CIRCUS_TENT]',
    # Box drawing characters
    '═': '=',
    '║': '|',
    '╔': '+',
    '╗': '+',
    '╚': '+',
    '╝': '+',
    '╠': '+',
    '╣': '+',
    '╦': '+',
    '╩': '+',
    '╬': '+',
    '╪': '-',
    '╫': '|',
    '╪': '+',
    '▀': '-',
    '▄': '-',
    '▌': '|',
    '▐': '|',
    '░': '.',
    '▒': '#',
    '▓': '@',
    '■': '#',
    '□': '#',
    '▪': '#',
    '▫': '#',
    '◙': 'o',
    '◘': 'o',
    '◚': 'o',
    '◛': 'o',
    '◜': 'o',
    '◝': 'o',
    '◞': 'o',
    '◟': 'o',
    '◢': '/',
    '◣': '\\',
    '◤': '/',
    '◥': '\\',
    '◦': '.',
    '◧': '#',
    '◨': '#',
    '◩': '#',
    '◪': '#',
    '◫': '#',
    '◰': '#',
    '◱': '#',
    '◲': '#',
    '◳': '#',
    '◰': '/',
    '◱': '\\',
    '◲': '\\',
    '◳': '/',
    '⬜': '#',
    '⬛': '#',
    '🟥': '#',
    '🟧': '#',
    '🟨': '#',
    '🟩': '#',
    '🟦': '#',
    '🟪': '#',
    '🟫': '#',
    '⬆️': '^',
    '⬇️': 'v',
    '⬅️': '<',
    '➡️': '>',
    '⬆️': '[U]',
    '⬇️': '[D]',
    '⬅️': '[L]',
    '➡️': '[R]',
    # Additional common Unicode
    '─': '-',
    '│': '|',
    '┌': '+',
    '┐': '+',
    '└': '+',
    '┘': '+',
    '├': '+',
    '┤': '+',
    '┬': '+',
    '┴': '+',
    '┼': '+',
}


class WindowsSafeConsole:
    """Wrapper around Console that replaces Unicode on Windows legacy consoles."""
    
    def __init__(self, console: Console):
        self._console = console
    
    def _sanitize_string(self, text: str) -> str:
        """Replace Unicode characters with ASCII alternatives."""
        for char, replacement in UNICODE_REPLACEMENTS.items():
            text = text.replace(char, replacement)
        return text
    
    def print(self, *args, **kwargs):
        """Print with Unicode replacement on Windows."""
        if IS_WINDOWS:
            processed_args = []
            for arg in args:
                if isinstance(arg, str):
                    arg = self._sanitize_string(arg)
                elif isinstance(arg, Exception):
                    # Handle exceptions - sanitize the exception message
                    arg = self._sanitize_string(str(arg))
                processed_args.append(arg)
            self._console.print(*processed_args, **kwargs)
        else:
            self._console.print(*args, **kwargs)
    
    def __getattr__(self, name):
        """Delegate all other attributes to the underlying console."""
        return getattr(self._console, name)


def get_console() -> WindowsSafeConsole:
    """Get a Console instance configured for the current platform.
    
    On Windows legacy consoles (cmd.exe, PowerShell), emojis may not display
    properly. This function creates a Console that handles this gracefully
    by wrapping it with emoji replacement support.
    
    Returns:
        WindowsSafeConsole: A wrapped Rich Console instance for Windows.
    """
    if IS_WINDOWS:
        # Create a basic Console, Rich will auto-detect the best mode
        inner_console = Console(
            force_terminal=True,
            legacy_windows=False,  # Disable legacy mode to avoid encoding errors
        )
        return WindowsSafeConsole(inner_console)
    else:
        inner_console = Console()
        return WindowsSafeConsole(inner_console)


# Default console instance for the framework
console = get_console()
