"""Unit tests for FlowBasedTestSuiteGenerator (Phase 4)."""

import pytest

from socialseed_e2e.project_manifest.flow_test_generator import (
    DATA_SCHEMA_TEMPLATE,
)


class TestFlowBasedTestSuiteTemplates:
    """Tests for FlowBasedTestSuiteGenerator templates."""

    def test_data_schema_template_renders(self):
        """Test that data schema template renders correctly."""
        from jinja2 import Template
        
        template = Template(DATA_SCHEMA_TEMPLATE)
        
        result = template.render(
            service_name="test-service",
            generation_timestamp="2024-01-01",
            dtos=[],
            endpoints=[],
            flows=[],
        )
        
        assert "test-service" in result
        assert "Auto-generated by socialseed-e2e" in result

    def test_data_schema_template_with_endpoints(self):
        """Test data schema template with endpoints."""
        from jinja2 import Template
        
        template = Template(DATA_SCHEMA_TEMPLATE)
        
        endpoints = [
            {"key": "get_users", "path": "/api/users"},
            {"key": "create_user", "path": "/api/users"},
        ]
        
        result = template.render(
            service_name="api-service",
            generation_timestamp="2024-01-01",
            dtos=[],
            endpoints=endpoints,
            flows=[],
        )
        
        assert "api-service" in result
        assert "get_users" in result
