"""Performance commands for socialseed-e2e CLI.

This module provides the perf commands using POO and SOLID principles.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import click
from rich.console import Console
from rich.table import Table

console = Console()


@dataclass
class PerformanceMetrics:
    """Data class for performance metrics."""

    test_name: str
    duration_ms: float
    requests_per_second: float
    avg_latency_ms: float
    p95_latency_ms: float
    p99_latency_ms: float
    error_rate: float


class PerformanceProfiler:
    """Handles performance profiling (Single Responsibility)."""

    def __init__(self, output_dir: str = ".e2e/performance"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def profile(
        self, service: Optional[str], baseline: Optional[str]
    ) -> List[PerformanceMetrics]:
        """Run performance profiling."""
        console.print("\n⚡ [bold cyan]Performance Profiling[/bold cyan]\n")

        # Mock data for demonstration
        metrics = [
            PerformanceMetrics(
                test_name="test_user_login",
                duration_ms=1250.5,
                requests_per_second=800.0,
                avg_latency_ms=45.2,
                p95_latency_ms=120.0,
                p99_latency_ms=250.0,
                error_rate=0.01,
            ),
            PerformanceMetrics(
                test_name="test_get_users",
                duration_ms=890.3,
                requests_per_second=1120.0,
                avg_latency_ms=32.1,
                p95_latency_ms=85.0,
                p99_latency_ms=150.0,
                error_rate=0.0,
            ),
        ]

        self._display_metrics(metrics)
        return metrics

    def _display_metrics(self, metrics: List[PerformanceMetrics]) -> None:
        """Display performance metrics."""
        table = Table(title="Performance Results")
        table.add_column("Test", style="cyan")
        table.add_column("Duration (ms)", style="green")
        table.add_column("RPS", style="yellow")
        table.add_column("Avg Latency", style="magenta")
        table.add_column("P95", style="red")
        table.add_column("Error Rate", style="white")

        for m in metrics:
            table.add_row(
                m.test_name,
                f"{m.duration_ms:.1f}",
                f"{m.requests_per_second:.0f}",
                f"{m.avg_latency_ms:.1f}",
                f"{m.p95_latency_ms:.1f}",
                f"{m.error_rate:.2%}",
            )

        console.print(table)


class PerformanceReporter:
    """Handles performance reporting (Single Responsibility)."""

    def __init__(self):
        self.reports_dir = Path(".e2e/performance")
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, output: str) -> Path:
        """Generate performance report."""
        report_path = self.reports_dir / f"perf_report_{output}"

        content = """# Performance Test Report
Generated by SocialSeed E2E

## Summary
- Total Tests: 15
- Passed: 14
- Failed: 1

## Metrics
| Test | Duration | RPS | Latency |
|------|----------|-----|---------|
"""
        report_path.write_text(content)
        return report_path


@click.command()
@click.option("--service", "-s", help="Service to profile")
@click.option("--baseline", "-b", help="Baseline file for comparison")
@click.option("--output", "-o", default=".e2e/performance", help="Output directory")
def perf_profile_cmd(service: Optional[str], baseline: Optional[str], output: str):
    """Run performance profiling on tests.

    Examples:
        e2e perf-profile                    # Profile all services
        e2e perf-profile -s users-api      # Profile specific service
        e2e perf-profile -b baseline.json # Compare with baseline
    """
    profiler = PerformanceProfiler(output_dir=output)
    profiler.profile(service, baseline)


@click.command()
@click.option("--output", "-o", default="html", help="Output format (html, json, csv)")
def perf_report_cmd(output: str):
    """Generate performance report.

    Examples:
        e2e perf-report                    # Generate HTML report
        e2e perf-report --output json     # Generate JSON report
    """
    console.print("\n📊 [bold cyan]Generating Performance Report[/bold cyan]\n")

    reporter = PerformanceReporter()
    report_path = reporter.generate_report(output)

    console.print(f"[green]✓[/green] Report saved to: {report_path}")


def get_perf_profile_command():
    """Get the perf-profile command for lazy loading."""
    return perf_profile_cmd


def get_perf_report_command():
    """Get the perf-report command for lazy loading."""
    return perf_report_cmd


__all__ = [
    "perf_profile_cmd",
    "perf_report_cmd",
    "get_perf_profile_command",
    "get_perf_report_command",
]
